[2025-02-26T15:11:38.740+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T15:11:38.749+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T15:11:38.756+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T15:11:38.757+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-26T15:11:38.850+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2025-02-25 00:00:00+00:00
[2025-02-26T15:11:38.856+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-26T15:11:38.858+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-02-26T15:11:38.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_connection', 'test_postgres_connection', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test_connection.py', '--cfg-path', '/tmp/tmprv6ncsmt']
[2025-02-26T15:11:38.860+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask test_postgres_connection
[2025-02-26T15:11:38.895+0000] {task_command.py:467} INFO - Running <TaskInstance: test_postgres_connection.test_postgres_connection scheduled__2025-02-25T00:00:00+00:00 [running]> on host 7abf5e180a33
[2025-02-26T15:11:38.932+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_connection' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T15:11:38.933+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-26T15:11:38.933+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-26T15:11:38.933+0000] {logging_mixin.py:190} INFO - Current task name:test_postgres_connection state:running start_date:2025-02-26 15:11:38.749864+00:00
[2025-02-26T15:11:38.933+0000] {logging_mixin.py:190} INFO - Dag name:test_postgres_connection and current dag run status:running
[2025-02-26T15:11:38.933+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-26T15:11:38.933+0000] {test_connection.py:51} INFO - Testing PostgreSQL connection
[2025-02-26T15:11:38.933+0000] {test_connection.py:62} INFO - Connecting to PostgreSQL at None:None/None
[2025-02-26T15:11:38.934+0000] {test_connection.py:89} ERROR - Connection test failed: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

[2025-02-26T15:11:38.934+0000] {python.py:240} INFO - Done. Returned value was: False
[2025-02-26T15:11:38.944+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-26T15:11:38.945+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=test_postgres_connection, task_id=test_postgres_connection, run_id=scheduled__2025-02-25T00:00:00+00:00, execution_date=20250225T000000, start_date=20250226T151138, end_date=20250226T151138
[2025-02-26T15:11:38.956+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-26T15:11:38.956+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-26T15:11:38.956+0000] {logging_mixin.py:190} INFO - Dag name:test_postgres_connection queued_at:2025-02-26 15:11:37.507127+00:00
[2025-02-26T15:11:38.956+0000] {logging_mixin.py:190} INFO - Task hostname:7abf5e180a33 operator:PythonOperator
[2025-02-26T15:11:38.998+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-26T15:11:39.007+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T15:11:39.007+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
